# Do you want to block interaction on protected block? (Default : true)
# if you set it to false, then player can right-click on protected block.
# ("false" option is only available for 1.13+ servers. If you want to help fix for 1.12.2- server, Github PR is welcome)
restrict_interactions: true

# If other player tires to break protected blocks, what message you want to print?
# You can use "[blockOwnerName]" or "[blockOwnerUUID]".
no_access_message: "Protected by : §b[blockOwnerName]§r §7(UUID: [blockOwnerUUID])§r"

# Should we prevent from liquid(lava, water) break protected blocks(Like torch, redstone etc.)? (Default : true)
prevent-liquid-break-protected-block: true

# World that are in this list will disable block protection when placing.
# (Blocks placed in the world prior to being added to this list are non-retroactively protected.)
disabled_protection_world:
- world_example____
- world_example2____

# Limit players bucket range. [Disabled by default(10.0). For enable, put : 3.4]
# This is because griefer can bypass right-click on the protected block with bucket
# (bucket reach is longer than normal block placing)
# If you want to enable, put 3.4
bucket_range: 10.0
# So, if player tries to click bucket out of range, then what message you want to print?
bucketOutOfRange: ""
# So, what bucket will you want to Block?
restricted_buckets:
- WATER_BUCKET
- LAVA_BUCKET
- BUCKET
- AXOLOTL_BUCKET
- COD_BUCKET
- TROPICAL_FISH_BUCKET
- TADPOLE_BUCKET
- SALMON_BUCKET
