name: ProtectOwnBlocks
version: '1.0-SNAPSHOT'
main: youtube.yomisyuram.protectownblocks.ProtectOwnBlocks
api-version: 1.13
commands:
  pob:
    description: Block protection mode will be "on" or "off"
    usage: /pob <on|off>
  ob:
    description: Alternative plugin of OwnBlocks
    usage: /pob <on|off>
  bp:
    description: Alternative plugin of BlockProtect
    usage: /pob <on|off>
  owning:
    description: Alternative plugin of BlockOwn
    usage: /pob <on|off>